### ISSUE TITLE
abort the request

### ISSUE THREAD

**Issue by rikakomoe** [kokororin/honoka#2]
Nowadays the fetch API accepts a [signal](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort) to cancel the request, being available in edge 16 (2017-10-17), firefox 57 (2017-11-14), chrome 67 (2018-05-29), and later.

How's it going on here?

**Comment by kirainmoe** [comment]
```js
let abortController = new AbortController();
let signal = abortController.signal;

honoka("http://somewhere", { signal }).then(res => {
    // ...
}).catch(e => {
    console.log(e);
});

abortController.abort();
```

returns:
```
Uncaught (in promise) DOMException: The user aborted a request.
```

It works on Chrome 70.0.3538.77, but not on Safari 11.2.1 (macOS High Sierra 10.13.6) (however demo provided by MDN isn't working either...). Tested current version of honoka.

**Comment by rikakomoe** [comment]
I guess at least the doc and type defination needs updating. qwq
